baseURL = 'https://c-b.io'
languageCode = 'en-us'
title = 'c-b.io'
theme = 'monochrome'
defaultContentLanguage = "en"
enableEmoji = true
paginate = 5
enableGitInfo = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]