baseURL = 'https://c-b.io/'
languageCode = 'en-us'
title = "c-b.io | RE // DFIR // CTF"
theme = 'siem'

[params]
  author = "Humpty/Tony"
  description = "Poking at binaries and chasing artifacts for shits and giggles."

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "dracula"
    lineNos = false
    guessSyntax = true
