[[navbar]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[navbar]]
  identifier = "blog"
  name = "Blog"
  url = "/blog"
  weight = 2
   [[navbar]]
    identifier = "cybersecurity"
    name = "Cybersecurity"
    url = "/tags/cybersecurity"
    parent = "blog"
    weight = 1
  [[navbar]]
    identifier = "homelab"
    name = "Homelab"
    url = "/tags/homelab"
    parent = "blog"
    weight = 2
  [[navbar]]
    identifier = "ham-radio"
    name = "Ham Radio"
    url = "/tags/ham"
    parent = "blog"
    weight = 3

[[navbar]]
  identifier = "contact"
  name = "Contact"
  url = "/contact"
  weight = 3