[[navbar]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

[[navbar]]
  identifier = "blog"
  name = "Blog"
  url = "/blog"
  weight = 2

[[navbar]]
  identifier = "contact"
  name = "Contact"
  url = "/contact"
  weight = 3